var app = angular.module("myApp", []);
app.controller("myCtrl", function($scope) {
  $scope.records = [
    {
      "id":1,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"29",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"234",
      "no_obra":"Vo.Bo.-0013/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Aguascalientes",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":2,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"30",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"235",
      "no_obra":"Vo.Bo.-0014/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Guadalajara",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":3,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"31",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"236",
      "no_obra":"Vo.Bo.-0015/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Guanajuato",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":4,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"32",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"237",
      "no_obra":"Vo.Bo.-0016/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Monterrey",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":5,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"33",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"238",
      "no_obra":"Vo.Bo.-0017/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Guadalajara",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":6,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"34",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"239",
      "no_obra":"Vo.Bo.-0018/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Aguascalientes",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":7,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"35",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"240",
      "no_obra":"Vo.Bo.-0019/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"San Luis Potosi",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":8,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"36",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"241",
      "no_obra":"Vo.Bo.-0020/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Guanajuato",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":9,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"37",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"242",
      "no_obra":"Vo.Bo.-0021/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Guadalajara",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":10,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"38",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"243",
      "no_obra":"Vo.Bo.-0022/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Guanajuato",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":11,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"39",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"244",
      "no_obra":"Vo.Bo.-0023/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Monterrey",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    },
        {
      "id":12,
      "created_at":"2018-11-08",
      "updated_at":"2018-11-08",
      "archivo":"40",
      "gaveta":"Accusantium iure aut quidem quam quia.",
      "expediente":"245",
      "no_obra":"Vo.Bo.-0024/1",
      "registro_de_oficios":"Nihil officiis nobis est alias molestias.",
      "fuente_financiera":"Sed quia maxime voluptas illo non veritatis non.",
      "ejercicio":"Dolores molestiae quis repellendus voluptatem ad.",
      "descripcion_obra":"Et cum quos voluptas hic ipsum ut sed. Nihil dolores sit quisquam dignissimos est est. Rerum ea modi molestias amet sit voluptatem sit. Aut totam impedit ducimus facilis rerum impedit.",
      "localidad":"Aguascalientes",
      "municipio":"Nobis nesciunt ut et ad ut sequi.",
      "aprobado":"Vero enim sequi rem ut eos possimus.",
      "contratado":"Corporis sint non sit ad.",
      "modificado":"Assumenda consequatur esse aperiam voluptas et sed laudantium non.",
      "no_contrato":"Voluptatem nulla laborum aspernatur vel aspernatur quo voluptas.",
      "plazo":"Reiciendis delectus et vel dolor asperiores.",
      "ejecucion":"Consequatur molestiae ex at tempore asperiores.",
      "asignacion":"Ut totam ratione eligendi nam dicta culpa.",
      "contratista":"Voluptate fugit blanditiis exercitationem reiciendis aliquid.",
      "inicio_programado":"1990-09-22",
      "termino_programado":"1985-07-10",
      "inicio_real":"1987-06-13",
      "termino_real":"1984-09-25"
    }
  ]
});